### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cecilieha**
Changed load-dietcheck according to updates in code.

### CODE REVIEW

**Comment by alketh** [comment]
@bsnouffer @cecilieha 
Please resolve check conflicts before I can merge into the master. The error most likely occured due to different columnnames in bec_dev and trunk models. To my knowledge Brian made sure that both bec_dev and trunk models can be used with report = TRUE (I never checked it myself). In case wrong columns are selected one solution might be to include a specialised print routine for each model type (bec_dev and trunk).

**Comment by alketh** [comment]
@cecilieha just realised that you forked from an old version of the code. Please make sure to use pull (or fork again from the current version) to get the latest changes.

**Comment by cecilieha** [comment]
Hi Alex,

I’m so sorry, it was my mistake!! I’m not that used to github, and did not try to update your code, but mine…So, so, sorry, I hope I didn’t mess things up..

Kind regards,

Cecilie


——————————————————————
Cecilie Hansen, PhD
Researcher
Ecosystem processes/Økosystemprosesser
Institute of Marine Research
Cecilie.hansen@imr.no
+47 984 31 016
——————————————————————



Fra: Alexander Keth <notifications@github.com>
Svar til: alketh/atlantistools <reply@reply.github.com>
Dato: tirsdag 1. november 2016 10.56
Til: alketh/atlantistools <atlantistools@noreply.github.com>
Kopi: Hansen Cecilie <cecilieha@IMR.no>, Mention <mention@noreply.github.com>
Emne: Re: [alketh/atlantistools] Add files via upload (#9)


@bsnouffer<https://github.com/bsnouffer> @cecilieha<https://github.com/cecilieha>
Please resolve check conflicts before I can merge into the master. The error most likely occured due to different columnnames in bec_dev and trunk models. To my knowledge Brian made sure that both bec_dev and trunk models can be used with report = TRUE (I never checked it myself). In case wrong columns are selected one solution might be to include a specialised print routine for each model type (bec_dev and trunk).

**Comment by alketh** [comment]
@cecilieha no worries :) You worked in your own fork from atlantistools. It's not possible for other users to change the sourcecode in alketh/atlantistools (I am the only one with write acces to the reop. However, I can add other users in the future.) It's good to know that other people use the code. Please make sure to get the most recent version as I have fundamentally changed how things work in atlantistools.

**Pull request closed without merging**
